FROM maven AS build
COPY . /home/app
RUN mvn -f /fome/app/pom.xml clean package -Dmaven.test.skip=true

FROM adoptopenjdk/openjdk11:ubi
COPY --from=build /home/app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
